# 1. On indique ici la version de docker-compose
version: '3.3'

# 2. Ici, on va lister l'ensemble des services (= nos containers)
services:

    # Hier, on a lancé manuellement cette commande
    # docker run --rm -p 8080:80 --name testphp8 -v "$PWD":/var/www/html php:8.1-apache

    # 2.1. On déclare un container qui sera nommé php
    php:
        image: php:8.1-apache
        ports:
            - 8080:80
        volumes:
            # 2.2. Avant la virgule : on se situe dans le dossier local
            # ./src => corrrespond à notre dossier local qui devra remonter dans notre conteneur

            # 2.3. Après la virgule : on se situe dans le conteneur
            # /var/www/html => correspond au dossier à l'intérieur de notre conteur qui réception le contenu de notre dossier source
            - ./src:/var/www/html

    # 3. On déclare un 2e container qui sera nommé php5
    php5:
        image: php:5.6-apache
        ports:
            - 8081:80
        volumes:
            # ./src => corrrespond à notre dossier local qui devra remonter dans notre conteneur

            # /var/www/html => correspond au dossier à l'intérieur de notre conteur qui réception le contenu de notre dossier source
            - ./src:/var/www/html